include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shawnwrt-index
PKG_VERSION:=1.0.2
PKG_RELEASE:=1

LUCI_TITLE:=ShawnWrt Index homepage
LUCI_DEPENDS:=+luci-base +luci-lua-runtime
LUCI_PKGARCH:=all
PKG_MAINTAINER:=Shawn Rain

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
