include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shawnwrt-channel-analysis
PKG_VERSION:=1.0.3
PKG_RELEASE:=2

LUCI_TITLE:=ShawnWrt MTK channel analysis
LUCI_DEPENDS:=+rpcd-mod-iwinfo
LUCI_PKGARCH:=all
PKG_MAINTAINER:=Shawn Rain

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
