#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

start_service() {
	local enabled
	config_load shawnwrt_ota
	config_get enabled auto enabled 0
	
	if [ "$enabled" = "1" ]; then
		procd_open_instance
		procd_set_param command /usr/bin/shawnwrt-ota-cron-helper
		procd_set_param respawn
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "shawnwrt_ota"
}
