include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shawnwrt-quickstart
PKG_VERSION:=0.12.7
PKG_RELEASE:=r1

LUCI_TITLE:=ShawnWrt QuickStart homepage
LUCI_DEPENDS:=+luci-base +luci-lua-runtime
LUCI_PKGARCH:=all
PKG_MAINTAINER:=Shawn Rain

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
