include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shawnwrt-ota
PKG_VERSION:=1.0.4
PKG_RELEASE:=r1

LUCI_TITLE:=LuCI support for ShawnWrt OTA
LUCI_DEPENDS:=+shawnwrt-ota
LUCI_PKGARCH:=all
PKG_MAINTAINER:=Shawn Rain

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
